### PR TITLE
Modifies README.md with aloha_mask_instructions.pdf content

### PR DESCRIPTION
**Pull request by kvnn**
This modifies the README.md with contents from aloha_mask_instructions.pdf, which will allow any Github visitors to view the contents immediately.

### CODE REVIEW

**Comment by anthonyjchriste** [comment]
Thank you!

**Comment by kvnn** [comment]
My pleasure. Are there any problems you could use help with on the
web/programming front?

**Comment by anthonyjchriste** [comment]
In regards to the web page, the hardest thing is keeping up with providing timely updates and instructions from the rest of the volunteer group. Most of the infrastructure is already there so at this stage that pretty much means editing and adding new markdown.

The only other major thing that's been on my wish list is to set up CI so that pushes to master automatically get deployed to our AWS EC2 instance.

I believe you're in the slack channel? We currently get volunteer requests through google forms which are then stored in google spreadsheets on drive. I know Patrick was talking about maybe setting up a rails app to do some of the heavy lifting of parsing the spreadsheets to organize the information. You might consider talking to him if that is something that interests you.

**Comment by kvnn** [comment]
> The only other major thing that's been on my wish list is to set up CI so
that pushes to master automatically get deployed to our AWS EC2 instance.

Can do.

I'm not in the slack channel, and haven't found a link. Do you mind
inviting Kriggen@gmail.com ?

**Pull request merged**
